import type { Metadata } from "next";
import { Karla, Nanum_Pen_Script } from "next/font/google";
import "./globals.css";
import "./components.css";
import { Navbar } from "@/components/Navbar/index";

const karla = Karla({
  variable: "--font-karla",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});
const nanumPenScript = Nanum_Pen_Script({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-nanum-pen-script",
});

export const metadata: Metadata = {
  title: "Hansraj Saini",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${karla.variable} ${nanumPenScript.variable} bg-background text-text antialiased dark:text-text-dark dark:bg-background-dark`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
